
SELECT * FROM customer_behavior limit 20;


-- Q1 Total revenue generated by male vs female customers?
Select gender, sum(purchase_amount) as revenue
from customer_behavior
group by gender;

-- Q2 Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer_behavior
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from customer_behavior);

-- Q3 Which are the products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as Avg_Rating
from customer_behavior
group by item_purchased
order by Avg_Rating desc
limit 5;

-- Q4 Compare average purchase amounts between and express shipping
select shipping_type, round(avg(purchase_amount),2) as Average_PurchaseAmount
from customer_behavior
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q5 Compare average spend and total revenue between subscribers and non-subscribers
select subscription_status,count(customer_id)as total_customers, round(avg(purchase_amount),2) as avg_spend, round(sum(purchase_amount),2) as total_revenue
from customer_behavior
group by subscription_status
order by total_revenue,avg_spend desc;

-- Q6 Which 5 products have the highest percentage of purchases with discounts applied
select item_purchased,round(Sum(Case when discount_applied = "Yes" then 1 else 0 end) / Count(*) * 100,0) as discount_rate
from customer_behavior
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7 Segment customers into New , returning and loyal according to number of previous purchases and show count 
with customer_type as (select customer_id,previous_purchases,case when previous_purchases = 1 then 'New' 
                       when previous_purchases between 2 and 10 then 'Returning'
                       else 'Loyal'
                       end as customer_segment
from customer_behavior
)
select customer_segment,count(*) as "Number of Customers"
from customer_type
group by customer_segment;

-- Q8 what are the top 3 most purchased products in each category
WITH item_count AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders
    FROM customer_behavior
    GROUP BY category, item_purchased
),
ranked_items AS (
    SELECT
        category,
        item_purchased,
        total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY total_orders DESC
        ) AS item_rank
    FROM item_count
)
SELECT
    category,
    item_purchased,
    total_orders,
    item_rank
FROM ranked_items
WHERE item_rank <= 3
ORDER BY category, item_rank;

-- Q9 customers who buy more than 5 times are likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer_behavior
where previous_purchases > 5
group by subscription_status;

-- Q10 what is revenue contribution per age group?
select age_group,sum(purchase_amount) as revenue
from customer_behavior
group by age_group
order by revenue desc;
